### ISSUE TITLE
Add DOI identifier to veppy

### ISSUE THREAD

**Issue by dandanxu** [solvebio/veppy#16]
Instructions here https://guides.github.com/activities/citable-code/

Will help with making veppy citable before publication

**Comment by davecap** [comment]
Added a DOI:

https://zenodo.org/record/495193#.WOULr3UrLmE

> David Caplan, Jeff Hull, Suraj Narwade, & Dandan. (2017). solvebio/veppy: Alpha [Data set]. Zenodo. http://doi.org/10.5281/zenodo.495193

**Comment by dandanxu** [comment]
yay! :) thanks
